# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8df9896d977653327dc7f64c2e7662b0c8541bd88f361fcacdef3b650b489035b6d316aa1058a3c2ec753a819553426a7890b858049c84a730e2326b5eaba113

test:
  secret_key_base: 137cd1786073275516cea0ad4e17bca14d15c41a2ee17919271a3ff2295dbd044d7f89d01a49574fb9850d22b8da4b2228dfcfbf9886a713bc250a7a86be9584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
